// <auto-generated />
using System;
using GestionPrestamosPersonales2023;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionPrestamosPersonales2023.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("GestionPrestamosPersonales2023.Adicionales", b =>
                {
                    b.Property<int>("AdicionalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("AdicionalesId");

                    b.ToTable("Adicionales");
                });

            modelBuilder.Entity("GestionPrestamosPersonales2023.Estudiantes", b =>
                {
                    b.Property<int>("EstudiantesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("EstudiantesId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("GestionPrestamosPersonales2023.Nacionalidades", b =>
                {
                    b.Property<int>("NacionalidadesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("NacionalidadesId");

                    b.ToTable("Nacionalidades");
                });

            modelBuilder.Entity("GestionPrestamosPersonales2023.Ocupaciones", b =>
                {
                    b.Property<int>("OcupacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Salario")
                        .HasColumnType("REAL");

                    b.HasKey("OcupacionId");

                    b.ToTable("Ocupaciones");
                });

            modelBuilder.Entity("GestionPrestamosPersonales2023.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Celular")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("F_Nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("L_Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("OcupacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("GestionPrestamosPersonales2023.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("F_Inicio")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("F_Vencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Monto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrestamoId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("GestionPrestamosPersonales2023.Tareas", b =>
                {
                    b.Property<int>("TareasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("TareasId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("GestionPrestamosPersonales2023.TiposTelefonos", b =>
                {
                    b.Property<int>("TiposTelofonosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.HasKey("TiposTelofonosId");

                    b.ToTable("TiposTelefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
